name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: TestApp.sln
      InnoSetup_Script: InnoScript.iss
      Installer_Output: Installer\

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install .NET 6 SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.x

      - name: Restore Dependencies
        run: dotnet restore $env:Solution_Name

      - name: Build Application
        run: dotnet build $env:Solution_Name --configuration ${{ matrix.configuration }}
      
      # Print contents of directory
      - name: Print contents of current directory
        run: |
          ls -R
      
      # Assuming your tests are part of the project
      - name: Run Tests
        run: dotnet test $env:Solution_Name --configuration ${{ matrix.configuration }}

      # Build the Inno Setup installer
      - name: Build Inno Setup Installer
        run: |
          iscc /O+ /DSIGNCODE="no" /DDEVBUILD="yes" "InnoScript.iss"
        shell: cmd

      # Sign the Inno Setup installer
      - name: Sign Inno Setup Installer
        run: |
          $signtool = "C:\Program Files (x86)\Microsoft SDKs\ClickOnce\SignTool\signtool.exe"
          & sign /tr  http://timestamp.digicert.com /td sha256 /fd sha256 /a .\Installer\setup.exe

      # Upload the installer
      - name: Upload Installer
        uses: actions/upload-artifact@v2
        with:
          name: Installer
          path: $env:Installer_Output

      - name: Notify on Success
        if: success()
        run: echo "Build and deployment succeeded!"

      - name: Notify on Failure
        if: failure()
        run: echo "Build and deployment failed!"
